repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua

  - repo: https://github.com/crate-ci/typos
    rev: v1.24.5
    hooks:
      - id: typos
        args: []
