return {
    diagnostic_signs = {
        error = "",
        warn = "",
        info = "",
        hint = "",
    },

    symbols = {
        File = "",
        Module = "",
        Namespace = "",
        Package = "",
        Class = "",
        Method = "",
        Property = "",
        Field = "",
        Constructor = "",
        Enum = "",
        Interface = "",
        Function = "",
        Variable = "",
        Constant = "",
        String = "",
        Number = "",
        Boolean = "",
        Array = "",
        Object = "",
        Key = "",
        Null = "",
        EnumMember = "",
        Struct = "",
        Event = "",
        Operator = "",
        TypeParameter = "",
    },

    folder_state = {
        folder_closed = "",
        folder_open = "",
        folder_empty = "◇",
    },
}
