local colors = require("ui.colorscheme.colors")

return {
  AerialLine = { ctermbg = colors.muted_bg, ctermfg = colors.normal_fg },
  AerialLineNC = { ctermbg = colors.muted_bg, ctermfg = colors.normal_fg },
  AerialNormal = { ctermbg = colors.normal_bg, ctermfg = colors.muted_fg },
  AerialGuide = { ctermbg = colors.debug },

  AerialBooleanIcon = { ctermfg = colors.muted_fg },
  AerialClassIcon = { link = "AerialBooleanIcon" },
  AerialConstantIcon = { link = "AerialBooleanIcon" },
  AerialConstructorIcon = { link = "AerialBooleanIcon" },
  AerialFieldIcon = { link = "AerialBooleanIcon" },
  AerialFunctionIcon = { link = "AerialBooleanIcon" },
  AerialMethodIcon = { link = "AerialBooleanIcon" },
  AerialNamespaceIcon = { link = "AerialBooleanIcon" },
  AerialNumberIcon = { link = "AerialBooleanIcon" },
  AerialOperatorIcon = { link = "AerialBooleanIcon" },
  AerialTypeParameterIcon = { link = "AerialBooleanIcon" },
  AerialPropertyIcon = { link = "AerialBooleanIcon" },
  AerialStringIcon = { link = "AerialBooleanIcon" },
  AerialVariableIcon = { link = "AerialBooleanIcon" },
  AerialEnumMemberIcon = { link = "AerialBooleanIcon" },
  AerialEnumIcon = { link = "AerialBooleanIcon" },
  AerialFileIcon = { link = "AerialBooleanIcon" },
  AerialModuleIcon = { link = "AerialBooleanIcon" },
  AerialPackageIcon = { link = "AerialBooleanIcon" },
  AerialInterfaceIcon = { link = "AerialBooleanIcon" },
  AerialStructIcon = { link = "AerialBooleanIcon" },
  AerialEventIcon = { link = "AerialBooleanIcon" },
  AerialArrayIcon = { link = "AerialBooleanIcon" },
  AerialObjectIcon = { link = "AerialBooleanIcon" },
  AerialKeyIcon = { link = "AerialBooleanIcon" },
  AerialNullIcon = { link = "AerialBooleanIcon" },
}
