name: CI

on:
  push:
  pull_request:

jobs:
  code-validation:
    name: Code validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
