name: CI

on:
  push:
  pull_request:

jobs:
  code-validation:
    name: Code validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install stylua
        run: cargo install stylua

      - name: Install typos
        run: cargo install typos-cli

      - name: Check formatting
        run: make formatter-check

      - name: Check spelling
        run: make spellchecker-check


